### ISSUE TITLE
why 100% quality will increase the volume

### ISSUE THREAD

**Issue by w-tim** [meowtec/Imagine#109]
Version:0.6.1
Mac 12.0.1

I am looking for tool to replace Imaginoptim(slow) and tinypng(can't be use it without internet). It's great to find out this one. Thank you!

Sometimes I am not expecting to lose the quality apparently(family photos), sometimes I need.(eg.website).

May I know why 100% quality will increase the volume of images?  100% should be means no-lossy or 99% original quality maybe?

**Comment by meowtec** [comment]
[Why does simply saving a JPEG at 100% quality in Photoshop increase filesize?](https://photo.stackexchange.com/questions/50789/why-does-simply-saving-a-jpeg-at-100-quality-in-photoshop-increase-filesize)

If you get a larger file, you should to skip it and just use the original file.

**Comment by w-tim** [comment]
thanks for quick reply
