### ISSUE TITLE
啥时候更新呀

### ISSUE THREAD

**Issue by setube** [meowtec/Imagine#129]
孩子都等麻了

**Comment by meowtec** [comment]
才搞了一半

**Comment by blacklein** [comment]
重写是electron还是swifty啊？imagine是我目前用的最舒服的图片减肥应用，windows和mac上都装了，感谢作者！

**Comment by meowtec** [comment]
> 重写是electron还是swifty啊？imagine是我目前用的最舒服的图片减肥应用，windows和mac上都装了，感谢作者！

Tauri

**Comment by blacklein** [comment]
那tauri支持苹果m1 chip吗？

**Comment by meowtec** [comment]
> 那tauri支持苹果m1 chip吗？

Yes

**Comment by blacklein** [comment]
继续等更新，超好用的app

**Comment by meowtec** [comment]
tauri 有些能力缺失，麻了。我还是基于 Electron 发个新版本吧。

**Comment by blacklein** [comment]
之前看到一篇文章，说是tauri在一些小细节上性能优于electron，但大方面还是有不足，还不太能替代electron，大概是这么个意思，还不够成熟吧，基于electron也好的

我用大佬的master代码构建苹果M1芯片arm64版的app是没问题的，希望大佬后面release能增加arm64的版本，可以的话还希望大佬能把app加入到homebrew，增加一个更便捷的安装和更新（主要是更新，主要是更新，主要是更新，重要的事说三遍，哈哈哈）途径

**Comment by meowtec** [comment]
> 之前看到一篇文章，说是tauri在一些小细节上性能优于electron，但大方面还是有不足，还不太能替代electron，大概是这么个意思，还不够成熟吧，基于electron也好的
> 
> 我用大佬的master代码构建苹果M1芯片arm64版的app是没问题的，希望大佬后面release能增加arm64的版本，可以的话还希望大佬能把app加入到homebrew，增加一个更便捷的安装和更新（主要是更新，主要是更新，主要是更新，重要的事说三遍，哈哈哈）途径

我想换成 tauri 的最主要原因是 electron 包体积太大了。
发到 homebrew 这一块没太了解过，因为平时不太用 `homebrew cask`. 有空我看下。

**Comment by blacklein** [comment]
https://docs.brew.sh/Cask-Cookbook
从官方文档看，加入homebrew基本上是全自动的，需要填写一些基本信息，用brew create命令，大佬有空不妨看下，我周围用homebrew的人很多，对推广应用是个不错的选择，发个brew install --cask imagine给朋友就能安装了，非常便利

**Comment by meowtec** [comment]
@SeTube @blacklein 
新发了一个 0.7.0 版本，支持 M1，试试吧。

**Comment by blacklein** [comment]
[Imagine.icns.zip](https://github.com/meowtec/Imagine/files/9390399/Imagine.icns.zip)
![Imagine](https://user-images.githubusercontent.com/69177971/185819759-830fa7a3-b933-4b53-9b26-698cc462cd0d.png)
已下载测试，提示应用已损坏，需要终端输入xattr -cr imagine.app消除属性后才能打开

另外大佬可否给mac图标改成统一风格的，像上面这样，与macOS系统看起来比较统一些，谢谢

**Comment by blacklein** [comment]
m1 macbook克隆源码到本地build好安装不会报已损坏的错误

**Comment by meowtec** [comment]
> m1 macbook克隆源码到本地build好安装不会报已损坏的错误

可能是因为本地编译是本地机器签名的，就不会有问题
