### ISSUE TITLE
反馈个问题

### ISSUE THREAD

**Issue by setube** [meowtec/Imagine#130]
图片拖入软件后再清空,然后再把图片删除会提示占用

**Comment by mplcoco** [comment]
无法通过文件打开的方式导入jpeg格式文件，因为默认可打开的文件扩展名里面不包含它。
另外就是在我把jpeg用拖拽的方式导入后，默认的导出方式变成了png格式，手动选择到jpg格式的话左上角那个绿灯就变成红色了，同时尝试以webp的方式导出正常。但是以拖拽的方式重新导入webp格式又是无法导入，本以为导出成webp再导出为jpg的想法也破灭了。于是放弃0.71版本，继续使用0.61，拖拽导入jpeg正常导出，但扩展名保持jpeg不变。尽管我的理解jpeg就是jpg但这意味着我仍然需要手动重新把扩展名更改为jpg。
以上就是我对我使用0.71版本过程中遇到的问题，就从我个人的使用而言，这次的更新很显然作者可能忽略了些什么。

**Comment by meowtec** [comment]
@mplcoco 发一下日志：C:\Users\用户名\AppData\Roaming\Imagine\logs 下面的 main.log

**Comment by SeTube** [comment]
打个比方:"我把"A"文件夹里的图片全部导入软件然后压缩,
等全部成功压缩后清空全部图片,然后移动或删除或其他操作压缩完毕的图片会提示文件占用
下个版本这个问题能修复吗?
