### ISSUE TITLE
最新版本有问题

### ISSUE THREAD

**Issue by SeTube** [meowtec/Imagine#132]
没法压缩图片,重复打开关闭也没有用,切换压缩格式也是这样

**Comment by meowtec** [comment]
什么系统版本？下载的哪个文件？

**Comment by SeTube** [comment]
win10 下载的是Imagine-0.7.0.exe
[https://github.com/meowtec/Imagine/releases/download/v0.7.0/Imagine-0.7.0.exe](https://github.com/meowtec/Imagine/releases/download/v0.7.0/Imagine-0.7.0.exe)

**Comment by meowtec** [comment]
已更新 v0.7.1
