### ISSUE TITLE
0.7.0版本有问题

### ISSUE THREAD

**Issue by Gguyi** [meowtec/Imagine#133]
不能压缩图片了，一直亮红灯。 用0.6.1就没问题。 两个.exe都试过了，都是一样的问题。

**Comment by meowtec** [comment]
试一下这个版本：
https://github.com/meowtec/Imagine/releases/download/untagged-fc353ba2de4ea698934c/Imagine-0.7.1.exe（不确定有没有权限下载）
如果没问题的就发布了。

**Comment by myhenji** [comment]
> 试一下这个版本： [https://github.com/meowtec/Imagine/releases/download/untagged-fc353ba2de4ea698934c/Imagine-0.7.1.exe（不确定有没有权限下载）](https://github.com/meowtec/Imagine/releases/download/untagged-fc353ba2de4ea698934c/Imagine-0.7.1.exe%EF%BC%88%E4%B8%8D%E7%A1%AE%E5%AE%9A%E6%9C%89%E6%B2%A1%E6%9C%89%E6%9D%83%E9%99%90%E4%B8%8B%E8%BD%BD%EF%BC%89) 如果没问题的就发布了。

這個鏈接下載不了，win10使用0.7.0也出現了樓主描述的問題。

**Comment by meowtec** [comment]
@Gguyi @myhenji 更新 0.7.1

**Comment by myhenji** [comment]
> 

0.7.1一切正常，作者辛苦。
