### ISSUE TITLE
ARM64是适配M1芯片的mac吗？装上直接提示让移除

### ISSUE THREAD

**Issue by abcmiao** [meowtec/Imagine#135]
![image](https://user-images.githubusercontent.com/13944985/185864256-ce49bace-2619-406b-95bc-99c4275959a5.png)

M1 12.5.1

0.7.0dmg没问题，Arm64dmg不行。

压缩图片也没问题，没出现他们说的压缩不了的情况

**Comment by meowtec** [comment]
这个问题是系统不允许未知来源导致的，可以搜一下办法开启。

但是 Intel 版本的没问题，Arm64 的不行，这个就比较奇怪。我研究下。

**Comment by meowtec** [comment]
try this: https://github.com/meowtec/Imagine/issues/129#issuecomment-1221670056

**Comment by meowtec** [comment]
详细参考 https://github.com/meowtec/Imagine/issues/136

**Comment by abcmiao** [comment]
OK，解决
