### ISSUE TITLE
360报毒

### ISSUE THREAD

**Issue by setube** [meowtec/Imagine#137]
木马文件：C:\Users\用户\AppData\Local\Temp\2DiagUGS50MAA3BVSADMCPgY3Sl\resources\app.asar.unpacked\bin\win32\x64\moz-cjpeg.exe
木马名称：HEUR/QVM202.0.B717.Malware.Gen
软件版本：0.7.1
系统版本：Windows 10 专业版 21H2 64位

**Comment by meowtec** [comment]
这个 exe 是我自己编译的，应该是误报

**Comment by meowtec** [comment]
BTW，我用火绒没有报毒。你试试 0.6.0 版本会报不？如果那个版本不会报，我把 moz-cjpeg.exe 还原回去

**Comment by SeTube** [comment]
测试过了,0.6.0版本不会报
