### ISSUE TITLE
How to Install in linux?

### ISSUE THREAD

**Issue by Hedronmx** [meowtec/Imagine#17]
I am running Elementary OS, how can I install this? :D

**Comment by meowtec** [comment]
I am building an AppImage app for linux, but stuck in downloading docker image.
Maybe success today.

**Comment by meowtec** [comment]
I have build an executable for linux: 

https://github.com/meowtec/Imagine/releases/tag/v0.1.4

**Comment by meowtec** [comment]
To install it, see http://appimage.org/ or README - [https://github.com/meowtec/Imagine#install-on-linux](install-on-linux)
