### ISSUE TITLE
Support for right click context menu 

### ISSUE THREAD

**Issue by puneetsngh** [meowtec/Imagine#23]
directly optimise individual files from the context menu or an entry to "open in imagine" for single or multiple file select

**Comment by meowtec** [comment]
Good idea.
Need to update windows registry via [winreg](https://www.npmjs.com/search?q=winreg) like Atom does.

**Comment by meowtec** [comment]
Have add `fileAssociations: {}` to electron builder config. Right click on picture files and we can find `open in Imagine`.
