### ISSUE TITLE
Problem saving file extension

### ISSUE THREAD

**Issue by Suleman-Elahi** [meowtec/Imagine#28]
The software works fine and I really like it when it comes to optimize images with **Imagine**. However I noticed that while saving an image to another file extension, the target file extension doesn't adds in the image name.

For example I am optimizing a PNG image and save it as Webp, then in the final file it still shows the PNG extension though the converted file is Webp. Same happens with the JPG image.

It is minor issue but I it needs to be fixed.

**Comment by meowtec** [comment]
Will fix soon.

**Comment by meowtec** [comment]
[v0.3.2](https://github.com/meowtec/Imagine/releases/tag/v0.3.2)
