### ISSUE TITLE
Doesn't optimize images on my computer

### ISSUE THREAD

**Issue by Suleman-Elahi** [meowtec/Imagine#34]
Hi, 

I am using Imagine on my Manajro Linux computer. I downloaded the AppImage and execute that. But after importing images, it doesn't optimize them. There is a red indicator appears, mean the images are not optimized.

Can you help with this ?

**Comment by meowtec** [comment]
Here is two way to find the reason:
1. Find the log file at `~/.config/imagine/log.log`
2. download binary files in [bin/linux](https://github.com/meowtec/Imagine/tree/dev/bin/linux), then execute `./moz-cjpeg -h` `./pngquant -h` to test whether they are working properly.

**Comment by Suleman-Elahi** [comment]
Hi again...
The "./moz-cjpeg -h " works fine. However, the other one seems to stuck !!!!!

![image](https://user-images.githubusercontent.com/24384996/35001260-73c67c30-fb0c-11e7-9b6d-a1b3ef034b62.png)

You can also see the contents of the log file here: https://paste.ee/p/56mF2

**Comment by edmael** [comment]
@Suleman-Elahi is your Manjaro install up to date?

**Comment by meowtec** [comment]
You can copy the shared library `libpng12.so.0` into `/usr/libs/`

**Comment by meowtec** [comment]
Fixed
