### ISSUE TITLE
win10不能正常使用。。。

### ISSUE THREAD

**Issue by meihangbo** [meowtec/Imagine#4]
启动弹出的错误
 ![image](https://user-images.githubusercontent.com/4393475/27669761-3b6e5654-5cbb-11e7-9b58-9728ce8b5c14.png)

关闭后弹出的错误
![image](https://user-images.githubusercontent.com/4393475/27669784-5e8a4666-5cbb-11e7-862f-7976f06be7aa.png)

**Comment by meowtec** [comment]
这真是一个莫名其妙的问题... 我装个虚拟机再看下

**Comment by meowtec** [comment]
这个是 makeSingleInstance 使用姿势不对造成的。
fix: ec4def99b12d683d34732b0ab4181a02ac9642fe
