### ISSUE TITLE
部分图片体积没减少，反而增加了

### ISSUE THREAD

**Issue by cyang812** [meowtec/Imagine#41]
在批量执行了400多张图片后发现，少部分的图片体积不仅没减少，还增加了。

另外如果要换一种格式，增加量可能达到400%多。

**Comment by meowtec** [comment]
这是正常的，我没想到有人会批量处理这么多图片。
这个可以考虑后续从交互上进行优化，比如把体积增大的图片高亮显示出来，增加一键排序功能，让体积增大的图片排到前面。

**Comment by cyang812** [comment]
或者做一个体积变大的就不保存了，只保存减少的。

**Comment by linhua55** [comment]
应该对 体积增大的图片，自动降低 图片质量，直到 体积减小为止。
比如色彩为 128时，体积增大了 4.4%，而色彩减小到 64后，体积减小了 7%，那么就以色彩 64 为最终结果

**Comment by Jerome-lara** [comment]
> 应该对 体积增大的图片，自动降低 图片质量，直到 体积减小为止。
> 比如色彩为 128时，体积增大了 4.4%，而色彩减小到 64后，体积减小了 7%，那么就以色彩 64 为最终结果

如果反而增大的原因是算法引起的，降低质量不是很好的方法。

**Comment by Jerome-lara** [comment]
@meowtec 大佬，好几个issue提到，期待更新。
