### ISSUE TITLE
Low compression rate need huge improvement

### ISSUE THREAD

**Issue by wangyjx** [meowtec/Imagine#51]
比较一下， https://squoosh.app/   
开源代码  https://github.com/GoogleChromeLabs/squoosh 

连个mozJPG和optiPNG压缩应该都没有支持吧
压缩率和压缩选项差劲

**Comment by meowtec** [comment]
JPEG:
Imagine: MozJPEG
squoosh: MozJPEG / Canvas API

PNG:
Imagine: pngquant
squoosh: OptiPNG / Canvas API

WebP: 都是 WebP

> 连个mozJPG和optiPNG压缩应该都没有支持吧

Imagine 的 README 里面就写了 mozjpeg，你在哪看到不支持 mozjpeg 的？

除了多了一个 Canvas 压缩，Imagine 的压缩方式比 squoosh 少很多吗？

> 压缩率和压缩选项差劲

来，发一下你的对比结果，包括原图。
