### ISSUE TITLE
请问您是怎样大的linux包，appimage是怎样打出来的？

### ISSUE THREAD

**Issue by ForeverSun** [meowtec/Imagine#52]
npm run release 并没有打包出

**Comment by meowtec** [comment]
```
"release": "npm run build && build -ml && build --win --ia32",
```

 - `npm run build` 前端代码构建
 -  `build -ml` 打 macOS 和 Linux 包
 -   `build --win --ia32` 打 Win32 的包

你是在 Mac 上编译吗？如果是 Windows 的话，是不能编译 Mac 包的，Linux 包可能也打不了。
如果要只打 Linux 的包，可以试试：

```sh
npm run build 
npx build -l
```

**Comment by ForeverSun** [comment]
谢谢
