### ISSUE TITLE
Update Electron?

### ISSUE THREAD

**Issue by tiotrom** [meowtec/Imagine#54]
This application seem not to be updated in a while. Are you still maintaining it? We made an AUR for it here https://aur.archlinux.org/packages/imagine-git/ and we wanted to know if anyone is keeping this one updated. Cheers!

**Comment by meowtec** [comment]
No plan  for new feature, but will update Electron and other dependencies to latest  today or tomorrow.

**Comment by meowtec** [comment]
The dependencies and source code has been updated but I have to delay the release because the building for win failed on macOS Catalina.

https://github.com/electron-userland/electron-builder/issues/4333

**Comment by meowtec** [comment]
released https://github.com/meowtec/Imagine/releases/tag/v0.5.1

**Comment by tiotrom** [comment]
Hey guys. We are unable to support the AUR version of this package anymore (unfortunately we are too busy). Are you able to help with that? https://aur.archlinux.org/packages/imagine-git/ Let us know, if you can't we will strive to maintain it but we can't promise. Cheers!
