### ISSUE TITLE
webp图片压缩，体积反而增大。

### ISSUE THREAD

**Issue by M956588010** [meowtec/Imagine#59]
你好，我按照你的代码重新编写代码后，发现使用webp图片进行压缩后，图片体积反而增大了，想问下这种情况是正常的吗？
操作系统：win10 64
工具：cwep.exe
图片格式:  webp，22KB
压缩后：webp,120KB

**Comment by meowtec** [comment]
正常。任何格式都可能变大。
如果批量操作，可以一键清除掉增大的。
