### ISSUE TITLE
How do I build/compile this project into releases?

### ISSUE THREAD

**Issue by rpelletierrefocus** [meowtec/Imagine#60]
Any pointers are appreciated.

**Comment by meowtec** [comment]
Step 1: Install Node.js (>=8.0)
Step 2: [Clone and install npm dependencies](https://github.com/meowtec/Imagine#build-and-contribute)
Step 3: Build
```sh
npm run build
npx electron-builder --win # build for windows. or -m (for macOS), -l (for Linux)
```

**Comment by rpelletierrefocus** [comment]
Thank and sorry, I should have and did figure that out myself. Just learning here. I appreciate your patience.
