### ISSUE TITLE
能设置默认转成webp格式吗？

### ISSUE THREAD

**Issue by zhujitop** [meowtec/Imagine#62]
现在默认是jpg格式，想转换成webp格式，还得一个一个的点击，图片太多了，太麻烦了。

希望增加一个软件功能，默认设置成什么格式。

然后导入图片之后，自动根据设置来就行了。

**Comment by meowtec** [comment]
可以，右上角有个弹窗，打开之后把 JPG 的 to JPG 改成 to WebP 就行
