### ISSUE TITLE
无法转换PNG格式的图片。

### ISSUE THREAD

**Issue by foxh1s** [meowtec/Imagine#64]
ver:  v0.5.1
sys: windows10-1909-18363.535

无法转换PNG格式的图片。

![14428](https://user-images.githubusercontent.com/34718973/76181229-622ca500-61fb-11ea-85f4-dc87f6fa1382.jpg)

[log.log](https://github.com/meowtec/Imagine/files/4304556/log.log)

**Comment by meowtec** [comment]
看看你的应用日志：
C:\Users\XXX\AppData\Roaming\Imagine\logs\*.log

**Comment by foxh1s** [comment]
> 看看你的应用日志：
> C：\ Users \ XXX \ AppData \ Roaming \ Imagine \ logs * .log

你好，日志已上传哦，在图片的下方，log.log

**Comment by meowtec** [comment]
看日志是调用 pngquant 命令写入失败，但是不知道为什么会失败。

手动执行看看能行不？
```
D:\Program Files\Imagine-0.5.1-ia32-win\resources\app.asar.unpacked\bin\win\pngquant.exe 128 C:\\Users\\QINZON~1\\AppData\\Local\\Temp\\imageOptimizer\\94307a096797ada55fb47c6b7260284e29b218b31d4b296959f909f5fcc17152.png -o C:\\Users\\QINZON~1\\AppData\\Local\\Temp\\imageOptimizer\\19636bf5c2727b5af6be71994ae3ee92.png
```

**Comment by foxh1s** [comment]
> 看日志是调用 pngquant 命令写入失败，但是不知道为什么会失败。
> 
> 手动执行看看能行不？
> 
> ```
> D:\Program Files\Imagine-0.5.1-ia32-win\resources\app.asar.unpacked\bin\win\pngquant.exe 128 C:\\Users\\QINZON~1\\AppData\\Local\\Temp\\imageOptimizer\\94307a096797ada55fb47c6b7260284e29b218b31d4b296959f909f5fcc17152.png -o C:\\Users\\QINZON~1\\AppData\\Local\\Temp\\imageOptimizer\\19636bf5c2727b5af6be71994ae3ee92.png
> ```

你好。手动执行可以。
我猜测是图片文件被占用的问题，我重启过一此系统，现在已经正常了。谢谢回复。
