### ISSUE TITLE
No progress bar is a big flaw没有进度条是很大缺陷

### ISSUE THREAD

**Issue by oldmenplus** [meowtec/Imagine#72]
No progress bar is a big flaw.I cannot know the progress of the conversion
没有进度条是很大缺陷，我不知道转换的进度

I did a comparative evaluation of the same type of image compression tools
我做了一个同类型的图片压缩工具的对比测评

Comparative evaluation summary picture
对比测评总结图片
https://i.loli.net/2020/08/26/y89fvUXB16c7VEw.jpg

Text summary
文字总结
https://oldmenplus.xyz/%E6%9C%AC%E5%9C%B0%E5%9B%BE%E7%89%87%E5%8E%8B%E7%BC%A9%E5%B7%A5%E5%85%B7%E6%B5%8B%E8%AF%84/

If you offend, please forgive me
如有冒犯，请原谅

This tool is one of the easier to use for the time being. I'm glad to use it
该工具是暂时我接触到的比较好用的几个之一，很高兴可以用到

_(-ω-`_)⌒)_

### Version
eg: 0.3.1

### Operating system (version and arch)
eg: Windows 10 x64

### Describe the bug
What happened?

**Comment by meowtec** [comment]
进度条是指全局的进度条（处理完成的数量 / 总数）还是针对每个任务的进度条？如果是全局的进度条，可以考虑加一下，不过交互可能得改。如果是针对每个任务的进度条，目前的技术方案加不了，因为底层是调用的可执行文件，它们没有提供进度接口。

**Comment by meowtec** [comment]
跑满 CPU 这个问题，是因为现在是单队列执行的，所以核心任务只使用了一个核。
这个倒是比较好改。

**Comment by oldmenplus** [comment]
> 进度条是指全局的进度条(处理完成的数量 / 总数)还是针对每个任务的进度条?如果是全局的进度条,可以考虑加一下,不过交互得改。如果是针对每个任务的进度条,目前的技术方案加不了,因为底层是调用的可执行文件,它们没有提供进度接口。

(´･Д･)」 当然是全局进度，要是要处理的文件多过六个就可能看不到进度了，要拖一下滚动条，而文件一多滚动条也有点卡顿

**Comment by oldmenplus** [comment]
> [CPU]，]，]
> • |

唔？ ( '-' )ノ)`-' )

**Comment by oldmenplus** [comment]
> 跑满 CPU 这个问题，是因为现在是单队列执行的，所以核心任务只使用了一个核。
> 这个倒是比较好改。

蔡B的AMD (´･Д･)」

**Comment by meowtec** [comment]
> > 进度条是指全局的进度条(处理完成的数量 / 总数)还是针对每个任务的进度条?如果是全局的进度条,可以考虑加一下,不过交互得改。如果是针对每个任务的进度条,目前的技术方案加不了,因为底层是调用的可执行文件,它们没有提供进度接口。
> 
> (´･Д･)」 当然是全局进度，要是要处理的文件多过六个就可能看不到进度了，要拖一下滚动条，而文件一多滚动条也有点卡顿

嗯，这是一个可以优化的点。
我当初开发这个的时候主要是从自己的需求出发，我没考虑过有人会一次处理那么多图片。。

**Comment by meowtec** [comment]
已经不再卡顿，而且并行处理，速度提高了几倍。
进度条还没加，打算在后面版本加上。
