### ISSUE TITLE
Windows Installer shouldn't require elevated privileges

### ISSUE THREAD

**Issue by Bios-Marcel** [meowtec/Imagine#76]
Hey,

I see no reason for an image optimizer to require administrative privileges. This kinda scares users off, at least it scares off me.
Is there any reason for doing this?

**Comment by meowtec** [comment]
The option `allowElevation` of `electron-builder` defaults to `true`. I will fix it.

Or please try https://github.com/meowtec/Imagine/releases/download/v0.5.1/Imagine-0.5.1-ia32-win.zip without installation.

**Comment by Bios-Marcel** [comment]
Thanks 👍
