### ISSUE TITLE
能否命令行调用软件压缩图片？

### ISSUE THREAD

**Issue by Severn17** [meowtec/Imagine#77]
Can the command line call can the command line call the software compressed image?If not, can you support it?
能否命令行调用软件压缩图片？如果没有的话能否支持？

If you offend, please forgive me, I'm glad to use it
如有冒犯，请原谅，很高兴可以用到

### Version

eg: 0.5.0

### Operating system (version and arch)

eg: Windows 10 x64

**Comment by 0x2CA** [comment]
https://github.com/kornelski/pngquant

**Comment by meowtec** [comment]
If you need to launch the app using command line, just find the binary file then execute it.

```sh
# MacOS
/Applications/Imagine.app/Contents/MacOS/Imagine
```

With some initial files:
```sh
/Applications/Imagine.app/Contents/MacOS/Imagine /path/to/image.png
```

To compress and save in one command, you should use pngquant or mozjpeg.

你找到对应的二进制文件，就能通过命令行启动。也可以带上默认的图片。如果希望一键压缩保存，应该使用 pngquant / mozjpeg.
