### ISSUE TITLE
[Feature Request] 麻烦增设 "转换后小于原图大小直接覆盖" 的选项

### ISSUE THREAD

**Issue by lyne408** [meowtec/Imagine#85]
许多人 常需要 保存 很多图片 至 本地磁盘或网盘.
PNG 格式的图片较大, 占用较多磁盘空间, 上传和下载都慢.
所以需要降低 gallery 的体积.

为不影响图片质量, 无损转换, 采用 更高压缩率的 WebP.
主要是转换是 PNG.
对于 JPG 等有损图片, 转为 WebP 往往更大, 没有必要,

所以 请 增设 "转换后小于原图大小直接覆盖" 的选项, 便于减少 gallery 大小.

**Comment by lyne408** [comment]
Yeah, 个人需求.
上面的需求只需: Shell Extension to File System Entity, 无损转换后, 保存较小的即可.
开源便于 DIY.
个人的非常见需求, 自行动手吧.
-_-

**Comment by meowtec** [comment]
0.6.0 版本会实现这个特性

**Comment by lyne408** [comment]
> 
> 
> 0.6.0 版本会实现这个特性

## Input 似乎只能是 `.jpg`, `.png`, 可以用 `libvips` 或是 `sharp` 啊, 支持挺多格式的

## 目前 缩小图片 大小还是 WebP `{quality:100, lossless: false}` 较为现实

2021, 浏览器开始支持 AVIF.

测试了几张 HEIF, AVIF 这类 HEVC 图片文件, lossless 后比起 其它格式的 小很多. 
但是转换较为耗时, 耗 CPU, 耗内存.

`quality: 100` 时 AVIF `{lossless: false}`  比 `lossless: true}` 大不了多少, 只减少约 1/6.
但  AVIF `{quality: 100, lossless: false}` 比  WebP `{quality: 100, lossless: false}` 大 0.5 倍.
只有 `quality: =< 75` 时, AVIF 才小于 Webp.

所以还是选择 WebP `{quality:100, lossless: false}`.

当然对于服务器, {quality:75} 是比较合适的.

**Comment by meowtec** [comment]
@lyne408 
后面应该会支持输出 AVIF
其他格式不常见或者兼容性不行，暂不考虑。

另外，加入新的编码器比较麻烦，目前是直接内置了二进制文件，需要分别考虑三端。
