### ISSUE TITLE
保存的文件没权限打开

### ISSUE THREAD

**Issue by ddosi** [meowtec/Imagine#90]
### Version
eg: 0.3.1

### Operating system (version and arch)
eg: Windows 10 x64

### Describe the bug
What happened?

### Logs

保存的文件没权限打开!!

**Comment by cxplay** [comment]
我也遇到了这个问题, 既没有打开的权限也没有编辑文件权限的权限, 现在可以通过注销重登陆解决这个问题.

**Comment by meowtec** [comment]
试试 0.6.1
