### ISSUE TITLE
Save and overwrite delete files!

### ISSUE THREAD

**Issue by pierzo** [meowtec/Imagine#91]
Version
0.6.0
Windows 7 x64

When user choose to save and overwrite file ( I use it a lot) program delete content of file. Output have right size (Adobe Bridge  show 0 kb) but you cant open file.  In windows native image  program you get "Windows Photo Viewer cannot open this image because it has been deleted or is in an inaccessible location". Summary, you lost your file. 

You program is great!
Regards

**Comment by meowtec** [comment]
This may relate to #90

**Comment by meowtec** [comment]
How about reboot windows?

**Comment by pierzo** [comment]
This is not a reboot issue. I tested it over the course of a few days.

**Comment by meowtec** [comment]
Please try v0.6.1 which should fix this issue.

If not, reopen this.
